services:
  backend:
    build: ./backend
    container_name: incidencias_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - incidencias_network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: incidencias_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - incidencias_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  incidencias_network:
    driver: bridge

volumes:
  uploads_data:
